# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Workspace\Project-Python\UsenDebugger\ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1591, 651))
        self.tabWidget.setIconSize(QtCore.QSize(64, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.tabOnsemi = QtWidgets.QWidget()
        self.tabOnsemi.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabOnsemi.setObjectName("tabOnsemi")
        self.groupBox_ThrTab1 = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_ThrTab1.setGeometry(QtCore.QRect(10, 180, 621, 201))
        self.groupBox_ThrTab1.setObjectName("groupBox_ThrTab1")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_ThrTab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 671, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OnsemiThrTab1_DT0 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT0.setMaximum(15)
        self.OnsemiThrTab1_DT0.setObjectName("OnsemiThrTab1_DT0")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT0)
        self.OnsemiThrTab1_DT1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT1.setMaximum(15)
        self.OnsemiThrTab1_DT1.setObjectName("OnsemiThrTab1_DT1")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT1)
        self.OnsemiThrTab1_DT2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT2.setMaximum(15)
        self.OnsemiThrTab1_DT2.setObjectName("OnsemiThrTab1_DT2")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT2)
        self.OnsemiThrTab1_DT3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT3.setMaximum(15)
        self.OnsemiThrTab1_DT3.setObjectName("OnsemiThrTab1_DT3")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT3)
        self.OnsemiThrTab1_DT4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT4.setMaximum(15)
        self.OnsemiThrTab1_DT4.setObjectName("OnsemiThrTab1_DT4")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT4)
        self.OnsemiThrTab1_DT5 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT5.setMaximum(15)
        self.OnsemiThrTab1_DT5.setObjectName("OnsemiThrTab1_DT5")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT5)
        self.OnsemiThrTab1_DT6 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT6.setMaximum(15)
        self.OnsemiThrTab1_DT6.setObjectName("OnsemiThrTab1_DT6")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT6)
        self.OnsemiThrTab1_DT7 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT7.setMaximum(15)
        self.OnsemiThrTab1_DT7.setObjectName("OnsemiThrTab1_DT7")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT7)
        self.OnsemiThrTab1_DT8 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT8.setMaximum(15)
        self.OnsemiThrTab1_DT8.setObjectName("OnsemiThrTab1_DT8")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT8)
        self.OnsemiThrTab1_DT9 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT9.setMaximum(15)
        self.OnsemiThrTab1_DT9.setObjectName("OnsemiThrTab1_DT9")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT9)
        self.OnsemiThrTab1_DT10 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT10.setMaximum(15)
        self.OnsemiThrTab1_DT10.setObjectName("OnsemiThrTab1_DT10")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT10)
        self.OnsemiThrTab1_DT11 = QtWidgets.QSpinBox(self.layoutWidget)
        self.OnsemiThrTab1_DT11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_DT11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_DT11.setMaximum(15)
        self.OnsemiThrTab1_DT11.setObjectName("OnsemiThrTab1_DT11")
        self.horizontalLayout_3.addWidget(self.OnsemiThrTab1_DT11)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_ThrTab1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 80, 601, 17))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(21)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_ThrTab1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 671, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OnsemiThrTab1_Lvl0 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl0.setMaximum(63)
        self.OnsemiThrTab1_Lvl0.setObjectName("OnsemiThrTab1_Lvl0")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl0)
        self.OnsemiThrTab1_Lvl1 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl1.setMaximum(63)
        self.OnsemiThrTab1_Lvl1.setObjectName("OnsemiThrTab1_Lvl1")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl1)
        self.OnsemiThrTab1_Lvl2 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl2.setMaximum(63)
        self.OnsemiThrTab1_Lvl2.setObjectName("OnsemiThrTab1_Lvl2")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl2)
        self.OnsemiThrTab1_Lvl3 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl3.setMaximum(63)
        self.OnsemiThrTab1_Lvl3.setObjectName("OnsemiThrTab1_Lvl3")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl3)
        self.OnsemiThrTab1_Lvl4 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl4.setMaximum(63)
        self.OnsemiThrTab1_Lvl4.setObjectName("OnsemiThrTab1_Lvl4")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl4)
        self.OnsemiThrTab1_Lvl5 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl5.setMaximum(63)
        self.OnsemiThrTab1_Lvl5.setObjectName("OnsemiThrTab1_Lvl5")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl5)
        self.OnsemiThrTab1_Lvl6 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl6.setMaximum(63)
        self.OnsemiThrTab1_Lvl6.setObjectName("OnsemiThrTab1_Lvl6")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl6)
        self.OnsemiThrTab1_Lvl7 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl7.setMaximum(63)
        self.OnsemiThrTab1_Lvl7.setObjectName("OnsemiThrTab1_Lvl7")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl7)
        self.OnsemiThrTab1_Lvl8 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl8.setMaximum(63)
        self.OnsemiThrTab1_Lvl8.setObjectName("OnsemiThrTab1_Lvl8")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl8)
        self.OnsemiThrTab1_Lvl9 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl9.setMaximum(63)
        self.OnsemiThrTab1_Lvl9.setObjectName("OnsemiThrTab1_Lvl9")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl9)
        self.OnsemiThrTab1_Lvl10 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl10.setMaximum(63)
        self.OnsemiThrTab1_Lvl10.setObjectName("OnsemiThrTab1_Lvl10")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl10)
        self.OnsemiThrTab1_Lvl11 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.OnsemiThrTab1_Lvl11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab1_Lvl11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab1_Lvl11.setObjectName("OnsemiThrTab1_Lvl11")
        self.horizontalLayout.addWidget(self.OnsemiThrTab1_Lvl11)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_ThrTab1)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 601, 17))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(17)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.OnsemiThr1_GenerateButton = QtWidgets.QPushButton(self.groupBox_ThrTab1)
        self.OnsemiThr1_GenerateButton.setGeometry(QtCore.QRect(550, 150, 61, 41))
        self.OnsemiThr1_GenerateButton.setAcceptDrops(False)
        self.OnsemiThr1_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThr1_GenerateButton.setCheckable(True)
        self.OnsemiThr1_GenerateButton.setAutoRepeat(False)
        self.OnsemiThr1_GenerateButton.setAutoExclusive(False)
        self.OnsemiThr1_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiThr1_GenerateButton.setDefault(True)
        self.OnsemiThr1_GenerateButton.setObjectName("OnsemiThr1_GenerateButton")
        self.OnsemiThrTab1_CodeText = QtWidgets.QTextBrowser(self.groupBox_ThrTab1)
        self.OnsemiThrTab1_CodeText.setGeometry(QtCore.QRect(10, 130, 531, 61))
        self.OnsemiThrTab1_CodeText.setObjectName("OnsemiThrTab1_CodeText")
        self.label_25 = QtWidgets.QLabel(self.tabOnsemi)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.label_25.setObjectName("label_25")
        self.onsemiTCmdPulse_Def = QtWidgets.QLineEdit(self.tabOnsemi)
        self.onsemiTCmdPulse_Def.setGeometry(QtCore.QRect(170, 10, 113, 20))
        self.onsemiTCmdPulse_Def.setInputMask("")
        self.onsemiTCmdPulse_Def.setObjectName("onsemiTCmdPulse_Def")
        self.onsemiTCmdSepPulse_Def = QtWidgets.QLineEdit(self.tabOnsemi)
        self.onsemiTCmdSepPulse_Def.setGeometry(QtCore.QRect(170, 30, 113, 20))
        self.onsemiTCmdSepPulse_Def.setInputMask("")
        self.onsemiTCmdSepPulse_Def.setObjectName("onsemiTCmdSepPulse_Def")
        self.label_26 = QtWidgets.QLabel(self.tabOnsemi)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tabOnsemi)
        self.label_27.setGeometry(QtCore.QRect(380, 30, 81, 21))
        self.label_27.setObjectName("label_27")
        self.onsemiTbit0_Def = QtWidgets.QLineEdit(self.tabOnsemi)
        self.onsemiTbit0_Def.setGeometry(QtCore.QRect(460, 10, 113, 20))
        self.onsemiTbit0_Def.setInputMask("")
        self.onsemiTbit0_Def.setObjectName("onsemiTbit0_Def")
        self.label_28 = QtWidgets.QLabel(self.tabOnsemi)
        self.label_28.setGeometry(QtCore.QRect(380, 10, 81, 21))
        self.label_28.setObjectName("label_28")
        self.onsemiTbit1_Def = QtWidgets.QLineEdit(self.tabOnsemi)
        self.onsemiTbit1_Def.setGeometry(QtCore.QRect(460, 30, 113, 20))
        self.onsemiTbit1_Def.setInputMask("")
        self.onsemiTbit1_Def.setObjectName("onsemiTbit1_Def")
        self.onsemiSetDefine_Button = QtWidgets.QPushButton(self.tabOnsemi)
        self.onsemiSetDefine_Button.setGeometry(QtCore.QRect(670, 10, 91, 41))
        self.onsemiSetDefine_Button.setObjectName("onsemiSetDefine_Button")
        self.groupBox_ThrTab2 = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_ThrTab2.setGeometry(QtCore.QRect(650, 180, 621, 201))
        self.groupBox_ThrTab2.setObjectName("groupBox_ThrTab2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_ThrTab2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 100, 671, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OnsemiThrTab2_DT0 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT0.setMaximum(15)
        self.OnsemiThrTab2_DT0.setObjectName("OnsemiThrTab2_DT0")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT0)
        self.OnsemiThrTab2_DT1 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT1.setMaximum(15)
        self.OnsemiThrTab2_DT1.setObjectName("OnsemiThrTab2_DT1")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT1)
        self.OnsemiThrTab2_DT2 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT2.setMaximum(15)
        self.OnsemiThrTab2_DT2.setObjectName("OnsemiThrTab2_DT2")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT2)
        self.OnsemiThrTab2_DT3 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT3.setMaximum(15)
        self.OnsemiThrTab2_DT3.setObjectName("OnsemiThrTab2_DT3")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT3)
        self.OnsemiThrTab2_DT4 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT4.setMaximum(15)
        self.OnsemiThrTab2_DT4.setObjectName("OnsemiThrTab2_DT4")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT4)
        self.OnsemiThrTab2_DT5 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT5.setMaximum(15)
        self.OnsemiThrTab2_DT5.setObjectName("OnsemiThrTab2_DT5")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT5)
        self.OnsemiThrTab2_DT6 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT6.setMaximum(15)
        self.OnsemiThrTab2_DT6.setObjectName("OnsemiThrTab2_DT6")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT6)
        self.OnsemiThrTab2_DT7 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT7.setMaximum(15)
        self.OnsemiThrTab2_DT7.setObjectName("OnsemiThrTab2_DT7")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT7)
        self.OnsemiThrTab2_DT8 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT8.setMaximum(15)
        self.OnsemiThrTab2_DT8.setObjectName("OnsemiThrTab2_DT8")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT8)
        self.OnsemiThrTab2_DT9 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT9.setMaximum(15)
        self.OnsemiThrTab2_DT9.setObjectName("OnsemiThrTab2_DT9")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT9)
        self.OnsemiThrTab2_DT10 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT10.setMaximum(15)
        self.OnsemiThrTab2_DT10.setObjectName("OnsemiThrTab2_DT10")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT10)
        self.OnsemiThrTab2_DT11 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.OnsemiThrTab2_DT11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_DT11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_DT11.setMaximum(15)
        self.OnsemiThrTab2_DT11.setObjectName("OnsemiThrTab2_DT11")
        self.horizontalLayout_5.addWidget(self.OnsemiThrTab2_DT11)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_ThrTab2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 80, 601, 17))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(21)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_6.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_6.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_6.addWidget(self.label_40)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_ThrTab2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 50, 671, 23))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.OnsemiThrTab2_Lvl0 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl0.setMaximum(63)
        self.OnsemiThrTab2_Lvl0.setObjectName("OnsemiThrTab2_Lvl0")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl0)
        self.OnsemiThrTab2_Lvl1 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl1.setMaximum(63)
        self.OnsemiThrTab2_Lvl1.setObjectName("OnsemiThrTab2_Lvl1")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl1)
        self.OnsemiThrTab2_Lvl2 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl2.setMaximum(63)
        self.OnsemiThrTab2_Lvl2.setObjectName("OnsemiThrTab2_Lvl2")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl2)
        self.OnsemiThrTab2_Lvl3 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl3.setMaximum(63)
        self.OnsemiThrTab2_Lvl3.setObjectName("OnsemiThrTab2_Lvl3")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl3)
        self.OnsemiThrTab2_Lvl4 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl4.setMaximum(63)
        self.OnsemiThrTab2_Lvl4.setObjectName("OnsemiThrTab2_Lvl4")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl4)
        self.OnsemiThrTab2_Lvl5 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl5.setMaximum(63)
        self.OnsemiThrTab2_Lvl5.setObjectName("OnsemiThrTab2_Lvl5")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl5)
        self.OnsemiThrTab2_Lvl6 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl6.setMaximum(63)
        self.OnsemiThrTab2_Lvl6.setObjectName("OnsemiThrTab2_Lvl6")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl6)
        self.OnsemiThrTab2_Lvl7 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl7.setMaximum(63)
        self.OnsemiThrTab2_Lvl7.setObjectName("OnsemiThrTab2_Lvl7")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl7)
        self.OnsemiThrTab2_Lvl8 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl8.setMaximum(63)
        self.OnsemiThrTab2_Lvl8.setObjectName("OnsemiThrTab2_Lvl8")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl8)
        self.OnsemiThrTab2_Lvl9 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl9.setMaximum(63)
        self.OnsemiThrTab2_Lvl9.setObjectName("OnsemiThrTab2_Lvl9")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl9)
        self.OnsemiThrTab2_Lvl10 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl10.setMaximum(63)
        self.OnsemiThrTab2_Lvl10.setObjectName("OnsemiThrTab2_Lvl10")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl10)
        self.OnsemiThrTab2_Lvl11 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.OnsemiThrTab2_Lvl11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThrTab2_Lvl11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OnsemiThrTab2_Lvl11.setObjectName("OnsemiThrTab2_Lvl11")
        self.horizontalLayout_7.addWidget(self.OnsemiThrTab2_Lvl11)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_ThrTab2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 601, 17))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(17)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_8.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_8.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_8.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_8.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_8.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_8.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_8.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_8.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_8.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_8.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_8.addWidget(self.label_52)
        self.OnsemiThr2_GenerateButton = QtWidgets.QPushButton(self.groupBox_ThrTab2)
        self.OnsemiThr2_GenerateButton.setGeometry(QtCore.QRect(540, 150, 71, 41))
        self.OnsemiThr2_GenerateButton.setAcceptDrops(False)
        self.OnsemiThr2_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiThr2_GenerateButton.setCheckable(True)
        self.OnsemiThr2_GenerateButton.setAutoRepeat(False)
        self.OnsemiThr2_GenerateButton.setAutoExclusive(False)
        self.OnsemiThr2_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiThr2_GenerateButton.setDefault(True)
        self.OnsemiThr2_GenerateButton.setObjectName("OnsemiThr2_GenerateButton")
        self.OnsemiThrTab2_CodeText = QtWidgets.QTextBrowser(self.groupBox_ThrTab2)
        self.OnsemiThrTab2_CodeText.setGeometry(QtCore.QRect(10, 130, 521, 61))
        self.OnsemiThrTab2_CodeText.setObjectName("OnsemiThrTab2_CodeText")
        self.groupBox_Index2a = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_Index2a.setGeometry(QtCore.QRect(10, 60, 291, 101))
        self.groupBox_Index2a.setObjectName("groupBox_Index2a")
        self.OnsemiCarrierPer_CodeText = QtWidgets.QTextBrowser(self.groupBox_Index2a)
        self.OnsemiCarrierPer_CodeText.setGeometry(QtCore.QRect(10, 50, 271, 41))
        self.OnsemiCarrierPer_CodeText.setObjectName("OnsemiCarrierPer_CodeText")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_Index2a)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 271, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_9.addWidget(self.label_53)
        self.OnsemiCarrierPer = QtWidgets.QSpinBox(self.layoutWidget3)
        self.OnsemiCarrierPer.setMaximum(2047)
        self.OnsemiCarrierPer.setObjectName("OnsemiCarrierPer")
        self.horizontalLayout_9.addWidget(self.OnsemiCarrierPer)
        self.OnsemiCarrierPer_GenerateButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.OnsemiCarrierPer_GenerateButton.setAcceptDrops(False)
        self.OnsemiCarrierPer_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiCarrierPer_GenerateButton.setCheckable(True)
        self.OnsemiCarrierPer_GenerateButton.setAutoRepeat(False)
        self.OnsemiCarrierPer_GenerateButton.setAutoExclusive(False)
        self.OnsemiCarrierPer_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiCarrierPer_GenerateButton.setDefault(True)
        self.OnsemiCarrierPer_GenerateButton.setObjectName("OnsemiCarrierPer_GenerateButton")
        self.horizontalLayout_9.addWidget(self.OnsemiCarrierPer_GenerateButton)
        self.groupBox_Index2b = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_Index2b.setGeometry(QtCore.QRect(310, 60, 391, 101))
        self.groupBox_Index2b.setObjectName("groupBox_Index2b")
        self.OnsemiDtCarrierPer_CodeText = QtWidgets.QTextBrowser(self.groupBox_Index2b)
        self.OnsemiDtCarrierPer_CodeText.setGeometry(QtCore.QRect(0, 50, 381, 41))
        self.OnsemiDtCarrierPer_CodeText.setObjectName("OnsemiDtCarrierPer_CodeText")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_Index2b)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 20, 381, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_10.addWidget(self.label_54)
        self.OnsemiDtx_Per = QtWidgets.QSpinBox(self.layoutWidget4)
        self.OnsemiDtx_Per.setMaximum(255)
        self.OnsemiDtx_Per.setObjectName("OnsemiDtx_Per")
        self.horizontalLayout_10.addWidget(self.OnsemiDtx_Per)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_10.addWidget(self.label_55)
        self.OnsemiDrx_Per = QtWidgets.QSpinBox(self.layoutWidget4)
        self.OnsemiDrx_Per.setMaximum(255)
        self.OnsemiDrx_Per.setObjectName("OnsemiDrx_Per")
        self.horizontalLayout_10.addWidget(self.OnsemiDrx_Per)
        self.OnsemiDeltaPer_GenerateButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.OnsemiDeltaPer_GenerateButton.setAcceptDrops(False)
        self.OnsemiDeltaPer_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiDeltaPer_GenerateButton.setCheckable(True)
        self.OnsemiDeltaPer_GenerateButton.setAutoRepeat(False)
        self.OnsemiDeltaPer_GenerateButton.setAutoExclusive(False)
        self.OnsemiDeltaPer_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiDeltaPer_GenerateButton.setDefault(True)
        self.OnsemiDeltaPer_GenerateButton.setObjectName("OnsemiDeltaPer_GenerateButton")
        self.horizontalLayout_10.addWidget(self.OnsemiDeltaPer_GenerateButton)
        self.groupBox_Inde3 = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_Inde3.setGeometry(QtCore.QRect(720, 60, 251, 101))
        self.groupBox_Inde3.setObjectName("groupBox_Inde3")
        self.OnsemiTxBurstPulse_CodeText = QtWidgets.QTextBrowser(self.groupBox_Inde3)
        self.OnsemiTxBurstPulse_CodeText.setGeometry(QtCore.QRect(10, 50, 231, 41))
        self.OnsemiTxBurstPulse_CodeText.setObjectName("OnsemiTxBurstPulse_CodeText")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_Inde3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 231, 25))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_11.addWidget(self.label_56)
        self.OnsemiTxBurstPulseCnt = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.OnsemiTxBurstPulseCnt.setMaximum(31)
        self.OnsemiTxBurstPulseCnt.setObjectName("OnsemiTxBurstPulseCnt")
        self.horizontalLayout_11.addWidget(self.OnsemiTxBurstPulseCnt)
        self.OnsemiTxBurstPulse_GenerateButton = QtWidgets.QPushButton(self.layoutWidget_7)
        self.OnsemiTxBurstPulse_GenerateButton.setAcceptDrops(False)
        self.OnsemiTxBurstPulse_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiTxBurstPulse_GenerateButton.setCheckable(True)
        self.OnsemiTxBurstPulse_GenerateButton.setAutoRepeat(False)
        self.OnsemiTxBurstPulse_GenerateButton.setAutoExclusive(False)
        self.OnsemiTxBurstPulse_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiTxBurstPulse_GenerateButton.setDefault(True)
        self.OnsemiTxBurstPulse_GenerateButton.setObjectName("OnsemiTxBurstPulse_GenerateButton")
        self.horizontalLayout_11.addWidget(self.OnsemiTxBurstPulse_GenerateButton)
        self.groupBox_Index4 = QtWidgets.QGroupBox(self.tabOnsemi)
        self.groupBox_Index4.setGeometry(QtCore.QRect(990, 60, 281, 101))
        self.groupBox_Index4.setObjectName("groupBox_Index4")
        self.OnsemiMeasDura_CodeText = QtWidgets.QTextBrowser(self.groupBox_Index4)
        self.OnsemiMeasDura_CodeText.setGeometry(QtCore.QRect(10, 50, 261, 41))
        self.OnsemiMeasDura_CodeText.setObjectName("OnsemiMeasDura_CodeText")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_Index4)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 20, 261, 25))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_13.addWidget(self.label_58)
        self.OnsemiMeasDura = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.OnsemiMeasDura.setMaximum(15)
        self.OnsemiMeasDura.setObjectName("OnsemiMeasDura")
        self.horizontalLayout_13.addWidget(self.OnsemiMeasDura)
        self.OnsemiMeasDura_GenerateButton = QtWidgets.QPushButton(self.layoutWidget_9)
        self.OnsemiMeasDura_GenerateButton.setAcceptDrops(False)
        self.OnsemiMeasDura_GenerateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OnsemiMeasDura_GenerateButton.setCheckable(True)
        self.OnsemiMeasDura_GenerateButton.setAutoRepeat(False)
        self.OnsemiMeasDura_GenerateButton.setAutoExclusive(False)
        self.OnsemiMeasDura_GenerateButton.setAutoRepeatInterval(100)
        self.OnsemiMeasDura_GenerateButton.setDefault(True)
        self.OnsemiMeasDura_GenerateButton.setObjectName("OnsemiMeasDura_GenerateButton")
        self.horizontalLayout_13.addWidget(self.OnsemiMeasDura_GenerateButton)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/neo_hei/Desktop/Onsemi-icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabOnsemi, icon, "")
        self.tabElmos = QtWidgets.QWidget()
        self.tabElmos.setObjectName("tabElmos")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/neo_hei/Desktop/elmos-icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabElmos, icon1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1287, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_ThrTab1.setTitle(_translate("MainWindow", "Index 5 (Thres Table 1)"))
        self.label_13.setText(_translate("MainWindow", "DT0"))
        self.label_14.setText(_translate("MainWindow", "DT1"))
        self.label_15.setText(_translate("MainWindow", "DT2"))
        self.label_16.setText(_translate("MainWindow", "DT3"))
        self.label_17.setText(_translate("MainWindow", "DT4"))
        self.label_18.setText(_translate("MainWindow", "DT5"))
        self.label_19.setText(_translate("MainWindow", "DT6"))
        self.label_20.setText(_translate("MainWindow", "DT7"))
        self.label_21.setText(_translate("MainWindow", "DT8"))
        self.label_22.setText(_translate("MainWindow", "DT9"))
        self.label_23.setText(_translate("MainWindow", "DT10"))
        self.label_24.setText(_translate("MainWindow", "DT11"))
        self.label.setText(_translate("MainWindow", "LVL0"))
        self.label_2.setText(_translate("MainWindow", "LVL1"))
        self.label_11.setText(_translate("MainWindow", "LVL2"))
        self.label_3.setText(_translate("MainWindow", "LVL3"))
        self.label_4.setText(_translate("MainWindow", "LVL4"))
        self.label_5.setText(_translate("MainWindow", "LVL5"))
        self.label_6.setText(_translate("MainWindow", "LVL6"))
        self.label_7.setText(_translate("MainWindow", "LVL7"))
        self.label_8.setText(_translate("MainWindow", "LVL8"))
        self.label_9.setText(_translate("MainWindow", "LVL9"))
        self.label_10.setText(_translate("MainWindow", "LVL10"))
        self.label_12.setText(_translate("MainWindow", "LVL11"))
        self.OnsemiThr1_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.label_25.setText(_translate("MainWindow", "Command pulse Define:"))
        self.onsemiTCmdPulse_Def.setText(_translate("MainWindow", "TDATA_L"))
        self.onsemiTCmdSepPulse_Def.setText(_translate("MainWindow", "TDATA_SEP_H"))
        self.label_26.setText(_translate("MainWindow", "Command separator Define:"))
        self.label_27.setText(_translate("MainWindow", "Bit1 Define:"))
        self.onsemiTbit0_Def.setText(_translate("MainWindow", "UNION_TBIT0"))
        self.label_28.setText(_translate("MainWindow", "Bit0 Define:"))
        self.onsemiTbit1_Def.setText(_translate("MainWindow", "UNION_TBIT1"))
        self.onsemiSetDefine_Button.setText(_translate("MainWindow", "Setting"))
        self.groupBox_ThrTab2.setTitle(_translate("MainWindow", "Index 6 (Thres Table 2)"))
        self.label_29.setText(_translate("MainWindow", "DT0"))
        self.label_30.setText(_translate("MainWindow", "DT1"))
        self.label_31.setText(_translate("MainWindow", "DT2"))
        self.label_32.setText(_translate("MainWindow", "DT3"))
        self.label_33.setText(_translate("MainWindow", "DT4"))
        self.label_34.setText(_translate("MainWindow", "DT5"))
        self.label_35.setText(_translate("MainWindow", "DT6"))
        self.label_36.setText(_translate("MainWindow", "DT7"))
        self.label_37.setText(_translate("MainWindow", "DT8"))
        self.label_38.setText(_translate("MainWindow", "DT9"))
        self.label_39.setText(_translate("MainWindow", "DT10"))
        self.label_40.setText(_translate("MainWindow", "DT11"))
        self.label_41.setText(_translate("MainWindow", "LVL0"))
        self.label_42.setText(_translate("MainWindow", "LVL1"))
        self.label_43.setText(_translate("MainWindow", "LVL2"))
        self.label_44.setText(_translate("MainWindow", "LVL3"))
        self.label_45.setText(_translate("MainWindow", "LVL4"))
        self.label_46.setText(_translate("MainWindow", "LVL5"))
        self.label_47.setText(_translate("MainWindow", "LVL6"))
        self.label_48.setText(_translate("MainWindow", "LVL7"))
        self.label_49.setText(_translate("MainWindow", "LVL8"))
        self.label_50.setText(_translate("MainWindow", "LVL9"))
        self.label_51.setText(_translate("MainWindow", "LVL10"))
        self.label_52.setText(_translate("MainWindow", "LVL11"))
        self.OnsemiThr2_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.groupBox_Index2a.setTitle(_translate("MainWindow", "Index 2a"))
        self.label_53.setText(_translate("MainWindow", "Carrier Tx/Rx Period"))
        self.OnsemiCarrierPer_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.groupBox_Index2b.setTitle(_translate("MainWindow", "Index 2b"))
        self.label_54.setText(_translate("MainWindow", "Delta Tx Period"))
        self.label_55.setText(_translate("MainWindow", "Delta Rx Period"))
        self.OnsemiDeltaPer_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.groupBox_Inde3.setTitle(_translate("MainWindow", "Index 3"))
        self.label_56.setText(_translate("MainWindow", "Tx Burst Pulse"))
        self.OnsemiTxBurstPulse_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.groupBox_Index4.setTitle(_translate("MainWindow", "Index 4"))
        self.label_58.setText(_translate("MainWindow", "Measurement Duration"))
        self.OnsemiMeasDura_GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOnsemi), _translate("MainWindow", "Onsemi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabElmos), _translate("MainWindow", "Elmos"))
